package com.virtual.box.core.proxy

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.virtual.box.base.util.log.L
/**
 * 代理Activity基类，以及用于占位的Activity
 */
open class ProxyActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        L.vd("ProxyActivity >> onCreate")
    }

    class P0 : ProxyActivity()
    class P1 : ProxyActivity()
    class P2 : ProxyActivity()
    class P3 : ProxyActivity()
    class P4 : ProxyActivity()
    class P5 : ProxyActivity()
    class P6 : ProxyActivity()
    class P7 : ProxyActivity()
    class P8 : ProxyActivity()
    class P9 : ProxyActivity()
    class P10 : ProxyActivity()
    class P11 : ProxyActivity()
    class P12 : ProxyActivity()
    class P13 : ProxyActivity()
    class P14 : ProxyActivity()
    class P15 : ProxyActivity()
    class P16 : ProxyActivity()
    class P17 : ProxyActivity()
    class P18 : ProxyActivity()
    class P19 : ProxyActivity()
    class P20 : ProxyActivity()
    class P21 : ProxyActivity()
    class P22 : ProxyActivity()
    class P23 : ProxyActivity()
    class P24 : ProxyActivity()
    class P25 : ProxyActivity()
    class P26 : ProxyActivity()
    class P27 : ProxyActivity()
    class P28 : ProxyActivity()
    class P29 : ProxyActivity()
    class P30 : ProxyActivity()
    class P31 : ProxyActivity()
    class P32 : ProxyActivity()
    class P33 : ProxyActivity()
    class P34 : ProxyActivity()
    class P35 : ProxyActivity()
    class P36 : ProxyActivity()
    class P37 : ProxyActivity()
    class P38 : ProxyActivity()
    class P39 : ProxyActivity()
    class P40 : ProxyActivity()
    class P41 : ProxyActivity()
    class P42 : ProxyActivity()
    class P43 : ProxyActivity()
    class P44 : ProxyActivity()
    class P45 : ProxyActivity()
    class P46 : ProxyActivity()
    class P47 : ProxyActivity()
    class P48 : ProxyActivity()
    class P49 : ProxyActivity()
    class P50 : ProxyActivity()
    class P51 : ProxyActivity()
    class P52 : ProxyActivity()
    class P53 : ProxyActivity()
    class P54 : ProxyActivity()
    class P55 : ProxyActivity()
    class P56 : ProxyActivity()
    class P57 : ProxyActivity()
    class P58 : ProxyActivity()
    class P59 : ProxyActivity()
    class P60 : ProxyActivity()
    class P61 : ProxyActivity()
    class P62 : ProxyActivity()
    class P63 : ProxyActivity()
    class P64 : ProxyActivity()
    class P65 : ProxyActivity()
    class P66 : ProxyActivity()
    class P67 : ProxyActivity()
    class P68 : ProxyActivity()
    class P69 : ProxyActivity()
    class P70 : ProxyActivity()
    class P71 : ProxyActivity()
    class P72 : ProxyActivity()
    class P73 : ProxyActivity()
    class P74 : ProxyActivity()
    class P75 : ProxyActivity()
    class P76 : ProxyActivity()
    class P77 : ProxyActivity()
    class P78 : ProxyActivity()
    class P79 : ProxyActivity()
    class P80 : ProxyActivity()
    class P81 : ProxyActivity()
    class P82 : ProxyActivity()
    class P83 : ProxyActivity()
    class P84 : ProxyActivity()
    class P85 : ProxyActivity()
    class P86 : ProxyActivity()
    class P87 : ProxyActivity()
    class P88 : ProxyActivity()
    class P89 : ProxyActivity()
    class P90 : ProxyActivity()
    class P91 : ProxyActivity()
    class P92 : ProxyActivity()
    class P93 : ProxyActivity()
    class P94 : ProxyActivity()
    class P95 : ProxyActivity()
    class P96 : ProxyActivity()
    class P97 : ProxyActivity()
    class P98 : ProxyActivity()
    class P99 : ProxyActivity()
}